### ISSUE TITLE
Protocol changes to eliminate the jackpot

### ISSUE THREAD

**Issue by smoelius** [TrueBitFoundation/Developer-Resources#5]
This is essentially a request for a pull from

  * https://github.com/smoelius/Developer-Resources.git

to the wiki:

  * https://github.com/TrueBitFoundation/Developer-Resources.wiki.git

The proposed changes to the protocol do the following.

  * Eliminate the jackpot.
  
  * Convert verifier payments into something better resembling a continuous revenue stream.

There are at least three reasons to motivate eliminating the jackpot.

A first reason is simplicity, as the logic to maintain the jackpot is extremely complex.

A second reason is that the jackpot system results in huge, infrequent, unreliable payments to verifiers.  Given the choice, verifiers would likely prefer smaller, more frequent, more reliable payments.

A third reason is that the jackpot's exponential decrease rule could potentially be weaponized, as demonstrated by the next example.  Suppose there are two verifiers, BigGuy and LittleGuy.  Suppose BigGuy is well-established and has capital to burn.  Suppose LittleGuy is a newcomer and is barely staying afloat.  Then BigGuy could submit extra verification bids every time LittleGuy submits a verification bid.  In this way, BigGuy would dilute LittleGuy's payments and potentially squeeze LittleGuy out of the verification market.

I apologize if the proposed changes resemble something that has already been considered, or if they suffer from some obvious flaw.

**Comment by teutsch** [comment]
Eliminating the jackpot is an interesting proposition, but the exponential decrease rule seems independent from the existence of the jackpot.  How would you prevent Sybil attacks without it?

**Comment by smoelius** [comment]
I have tried to structure things so that the verifier* is selected in the same way that the solver is selected, i.e., whoever's transaction happens to get included in a block.  So, in that sense, I think a Sybil attack is no longer applicable.  (I could be wrong, or I could be misunderstanding the type of Sybil attack that you have in mind.)

\* There are actually two types verifiers the way that I have structured things.  In this particular case, I mean Verifier A.

**Comment by hswick** [comment]
How are verifiers incentivized to verify tasks without the jackpot? Verifier's receiving a solver's deposit or even the Task Reward isn't sufficient, as it is expected that Solver's make mistakes very rarely. 

The need for the exponential drop off stems from there being an array of challengers. And you have to have an array, because if there was only one challenger then it would be easy for only a solver to challenge their own solution.

Solver's are currently selected by whoever calls `registerForTask` first. It isn't really by lottery. So in your current writeup, a Solver could registerForTask and challenge their own task fairly easily by paying a higher gas price (or frontrunning). The reason for this is that non gameable randomness on Ethereum is rather difficult. 

Could you highlight what the differences are between Verifier A and Verifier B? It wasn't very clear to me.

**Comment by smoelius** [comment]
If Solver and Verifier A perform only correct computations, then they each have an equal shot at receiving the task reward.

There are two types of verifiers (A and B), in part, because Solver can challenge their own solution.

The anticipated normal operation of the protocol (slightly abbreviated) is as follows.

* Solver commits two solutions, one correct, one incorrect.
* Verifier A (which is possibly Solver) identifies the incorrect solution.
* Solver or Verifier A receive the task reward (with equal probability).

Between the second and third bullets, any number of verifiers can challenge the correct solution, one at a time, as Verifier B.  But, as you point out, this part of the protocol should be used only rarely.

I am anticipating the possibility that I have oversimplified the protocol so as to introduce a vulnerability.  But, if I have not, then I hope the simplicity will be regarded as a benefit.

**Comment by teutsch** [comment]
As @hswick pointed out, the system has no reason to trust Verifier A.  Moreover, Verifier B is essentially the construction given in the TrueBit whitepaper.  Therefore including Verifier A appears to be superfluous.

**Comment by smoelius** [comment]
I don't think that assessment is quite right.

The non-existence of Verifier B, or all Verifier B losing their respective verification games, is reason to trust Verifier A.  In other words, Verifier B exists to keep Verifier A honest.

Regarding "Verifier B is essentially the construction given in the TrueBit whitepaper", there are at least two differences.

* When Verifier B challenges, he already knows which solution is the one claimed correct by Solver.  (This identification is essentially the work done by Verifier A.)  The verifiers in the TrueBit whitepaper are not given this knowledge.

* Each Verifier B is selected in the same (cleverly) simple way that the TrueBit whitepaper selects Solver: whoever's transaction happens to get included in a block.  So, for example, there is no sharing of a payout among the Verifier B, like there is among the verifiers in the TrueBit whitepaper.

**Comment by hswick** [comment]
Hmmm, it seems that with the assumption that Verifier A (is usually the solver) there doesn't need to be a forced error. 

If the Solver is already denoting which solution they believe to be the 'correct' one (by being a Verifier A), and it is deemed correct if no Verifier B's challenge it, then we could simplify this by having the Solver only submit the solution they deem 'correct'. 

Solver submits one solution, if a verifier deems it incorrect, they challenge and play a verification game. This is basically our current setup with the doge bridge (scrypt-interactive). Which is fine, but the verifiers are assumed to be altruistic. And once again there is no incentive.

**Comment by teutsch** [comment]
> When Verifier B challenges, he already knows which solution is the one claimed correct by Solver. (This identification is essentially the work done by Verifier A.) The verifiers in the TrueBit whitepaper are not given this knowledge.

Revealing the "correct" solution leaves the system vulnerable to "Incorrect Secondary Solution" attacks (see p. 41 of whitepaper).  What happens if both of the Solver's solutions are incorrect and there is a forced error?

>Each Verifier B is selected in the same (cleverly) simple way that the TrueBit whitepaper selects Solver: whoever's transaction happens to get included in a block. So, for example, there is no sharing of a payout among the Verifier B, like there is among the verifiers in the TrueBit whitepaper.

How many Verifier B's do you permit per task?

**Comment by smoelius** [comment]
@hswick I agree with your sentiment that if Verifier A were **always** Solver, then there would be no need for him to produce two solutions.

But in regard to what you actually said, "Verifier A (is **usually** the solver)" (emphasis added)...

Verifier A has a 50% chance of receiving the task reward.  So, there is clearly incentive for verifiers other than Solver to compute and challenge one or both of Solver's solutions.

But, fundamentally, the selection of Verifier A (and of Solver, and of each Verifier B) is a race condition.  Are you suggesting that Solver's chances of winning that race are somehow elevated compared to other verifiers?

**Comment by smoelius** [comment]
> Revealing the "correct" solution leaves the system vulnerable to "Incorrect Secondary Solution" attacks (see p. 41 of whitepaper). What happens if both of the Solver's solutions are incorrect and there is a forced error?

Verifier A can challenge one or both solutions.  If Verifier A challenges the solution that Solver claims is correct (which is necessarily the case if Verifier A challenges both solutions), then they play a verification game.

> How many Verifier B's do you permit per task?

There is no limit.  Each one (one by one) plays a verification game with Solver over the solution that Solver claims is correct.

**Comment by teutsch** [comment]
How much is the Verifier's expected gain for participating?

As I understand, Verifiers A & B only receive rewards for finding bugs, so without any errors they expect to gain nothing.  Thus Verifiers lack incentive to show up, which means that the Solver can get bogus stuff onto the blockchain.

**Comment by smoelius** [comment]
> How much is the Verifier's expected gain for participating?

@teutsch To answer your question precisely would be challenging, in part, because it depends upon a verifier's chances of getting selected as Verifier A or B.  (In regard to getting selected as Verifier A, see my question to @hswick three comments ago.)

**If** a verifier is selected as Verifier A, then he has a 50% chance of receiving the task reward.

Solver produces two solutions.  So, at least one of them must be incorrect.  In that sense, there is always at least one error for Verifier A to find.  In other words, even if Solver does his job perfectly, Verifier A still has a 50% chance of receiving the task reward.

If Verifier A challenges only one solution, then, yes, Verifier B only stands to gain if their is a bug in the other solution.

But, presumably, if I were a verifier, I would do something like the following.
* Perform the task computation.
* Challenge one solution (under normal circumstances) in attempt to become Verifier A.
* If not selected as Verifier A, then check whether the real Verifier A challenged the same solution that I would have, and, if not, then challenge that other solution in attempt to become Verifier B.

The point that I am trying to make here is that the work required to participate as Verifier A or B is not that different.

**Comment by hswick** [comment]
> But, fundamentally, the selection of Verifier A (and of Solver, and of each Verifier B) is a race condition. Are you suggesting that Solver's chances of winning that race are somehow elevated compared to other verifiers?

@smoelius Yes, the race condition means the incentives could be broken in practice. A Solver has the advantage of knowing when they submit their solution, and they can simply pay a higher gas price. There also mining attacks where a Solver would have an incentive to front run other tx's or even delay other tx's. 

If it turns out that the Solver gets to normally be Verifier A by any of the above methods, and this fact is known to users, then there is a higher incentive to Solve instead of Verify.

**Comment by teutsch** [comment]
I think a Cartel attack is also possible.  The attacker creates a smart contract which pays interest to anyone who loans the attacker a deposit.  The attacker pays for this interest by creating Sybil identities and winning the Solver/Verifier A elections more often.  There's no cost or risk for hodlers to participate.

Reusing Verifier A's work as Verifier B is a useful scheme if we assume that the Verifier does indeed wish to participate in verification games.

**Comment by smoelius** [comment]
> Solver has the advantage of knowing when they submit their solution...

@hswick Suppose we were to, say, require Verifier A to submit the hash of the block following the one containing the Solver's submission.  Would you agree that would defeat any advantage Solver has of knowing when they submit their solutions?

In regard to paying a higher gas price, front running, and delaying transactions: to be clear, these do not confer an advantage unique to Solver (unless I am misunderstanding).  Nonetheless, I appreciate your point that

> If it turns out that the Solver gets to normally be Verifier A by any of the above methods, and this fact is known to users, then there is a higher incentive to Solve instead of Verify.

and this, in turn, increases a Solver's chances of getting a bogus computation onto the blockchain.

Suppose we were to require Solver to post a slightly higher `minDeposit` than a verifier.  In other words, when Solver loses a verification game, he pays a slightly higher price than when a verifier loses a verification game.  TrueBit would set this higher `minDeposit` based upon how often such bogus computation attacks were being attempted in the wild.  Could you still then see a problem?

**Comment by teutsch** [comment]
When

**Comment by smoelius** [comment]
> I think a Cartel attack is also possible. The attacker creates a smart contract which pays interest to anyone who loans the attacker a deposit. The attacker pays for this interest by creating Sybil identities and winning the Solver/Verifier A elections more often. There's no cost or risk for hodlers to participate.

@teutsch I am not sure that I completely understand.  Is the smart contract essential to your argument?

**Comment by teutsch** [comment]
The smart contract guarantees that the hodler receives his interest without having to trust the attacker.

It seems to me that the computation only becomes reuseable if the Verifier A election happens *after* the computation has taken place.  If the election happens first, then whoever is not elected will not have incentive to perform the computation.  A Task Giver who knows the solution to his own task has a significant advantage, hence it is not secure to elect the first agent that provides an answer.

**Comment by smoelius** [comment]
> The smart contract guarantees that the hodler receives his interest without having to trust the attacker.

Is the attacker's role simply to create the contract?  What guarantees that the contract can pay the interest (without the holder having to trust the attacker)?

> It seems to me that the computation only becomes reuseable if the Verifier A election happens after the computation has taken place. If the election happens first, then whoever is not elected will not have incentive to perform the computation. ...

What you are describing sounds like what is in my current write up.  In order to be a candidate for election as Verifier A, a verifier has to challenge one or both solutions.  And, in order to challenge a solution, a verifier has to have performed the computation.  So, in that sense, the election does happen after the computation has taken place.  Am I misunderstanding your objection?

**Comment by hswick** [comment]
The smart contract is just meant to pool the Mob's capital in a trustless way. The guarantees are based on whether the lenders are making a return or not.

A verifier doesn't have to run the computation before challenging, they probably should to not end up in a losing verification game, but no one is making them do it.

**Comment by teutsch** [comment]
One can either have:

1. an election round before computation begins, or 
2. the race to submit a solution can begin immediately.

There are tradeoffs in either case.  TrueBit follows option 1 because it's computationally less expensive and easier to estimate net rewards after factoring in computation costs.  

This [manuscript](http://people.cs.uchicago.edu/~teutsch/papers/cryptogame.pdf) discusses both options and refers to them respectively as "consensus-contracts" and "consensus-competitions."
